### ISSUE TITLE
Mac plugin

### ISSUE THREAD

**Issue by rankify** [GuitarML/SmartGuitarAmp#20]
Any mac vst version in the making?

**Comment by GuitarML** [comment]
@rankify  Yes! Should be up in the website in the next week or two. Is there a preference among Mac users between AU or VST3 format? Or would it be helpful to do both.

**Comment by rankify** [comment]
AU is for Pro Tools, so both would be helpful

**Comment by GuitarML** [comment]
The Mac version is up! Easier to do than I thought.

**Comment by rankify** [comment]
You tested it? Garageband won't find it

**Comment by GuitarML** [comment]
I tested the AU in GarageBand, try that one and in the meantime I'll troubleshoot the VST3. Probably just my being unfamiliar with where things should go on Mac, sorry about that.

**Comment by mishushakov** [comment]
@rankify @GuitarML  i'm certain GarageBand only supports AU

**Comment by GuitarML** [comment]
I'm still having issues loading the vst3 in Reaper on Mac, it seems to recognize that it's there, and I get a security prompt saying it doesn't recognize the download site. I click to allow it in the security settings, but it still doesn't show up in Reaper. Rebooted, tried putting the VST3 in some other locations, same result. The AU works fine though!

**Comment by mishushakov** [comment]
@GuitarML try the trick
https://www.macworld.co.uk/how-to/mac-app-unidentified-developer-3669596

you'll need apple developer account to sign your code ($100/year)

i would gladly pay for the signed distribution so you can recoup the costs and even have some budget for the cool stuff

i've seen people all over internet complaining how this only works on Windows
wanna mac version? [f*ck you, pay me!](https://www.youtube.com/watch?v=jVkLVRt6c1U)

you're not a charity Keith, you don't owe us sh*t!

**Comment by GuitarML** [comment]
Haha yeah I probably won't pay for that, I don't think that's the issue anyway, you also have to verify the AU plugin. 

It actually doesn't bother me if people complain (legitimately or otherwise) about the free software I put out. The amount I've learned by doing this is worth the effort. I'd rather hear what people have to say so I can learn from it. I appreciate  the support though @mishushakov!

**Comment by NLeRoy917** [comment]
Thanks for this! Just installed to try out. I ran into the incompatibility issue due to an "unverified developer". If you simply run this command in the terminal: `xattr -rd com.apple.quarantine <path to .component>` you can get it out of quarantine and Logic won't yell at you.

**Comment by GuitarML** [comment]
I didn’t know about the command line option, thanks for the tip!
