### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by kevta** [GuitarML/SmartGuitarAmp#21]
Apologies if redudant.

Downloaded the vst recently, put it into Ableton and it's using 80%-105% of my CPU. I have an older i5, but I've never encountered this problem with any VST before. Using the same methods too, placing it in the requisite folder, loading it in, placing it in the effects chain. When I turn it off, the CPU usage obviously drops.

Not sure what's causing this.

**Comment by GuitarML** [comment]
Yes, high CPU usage is a drawback of the WaveNet model. There are probably some things that can be done to improve cpu usage some, but I think a different model entirely will be needed to reduce CPU usage to compare with other plugins.

If you look at the research paper this is based on, the Wavenet model was able meet the requirement of running in real time, but not much better. That's probably why they open sourced the model (see WaveNetVA repository). It's an interesting science experiment but not really feasible as a commercial plugin. 

The LSTM model from the paper achieved about 4-5x faster speeds, and that's what I'm working on developing now.
