### ISSUE TITLE
Save/load plugin state across sessions

### ISSUE THREAD

**Issue by usdivad** [GuitarML/SmartGuitarAmp#22]
I've started using SmartGuitarAmp and SmartGuitarPedal in some music projects and one of the biggest features I want is to have the plugin state be retained across DAW sessions, so that I don't have to keep reloading models and adjusting parameters when reopening a saved project -- I can imagine that other users could find this feature useful as well.

Happy to tackle this myself! The main question I have is whether it'd be better to save the model JSON directly as part of the state (which would remove reliance on external files but increase file size) or just the model path (which would save space but break if the model file gets moved/deleted). I'm leaning towards the latter, since for now it's simple enough for users to reload a new model if they happen to move or delete them after saving. Curious what folks feel like would be best though, or any other solutions I'm not thinking of.

It'd probably be good to add similar functionality to the SmartGuitarPedal as well, but figured we could keep discussion to a single issue for convenience.

**Comment by mishushakov** [comment]
hey there,
glad to see you back!

i've been thinking about the same thing lately
when downloading presets i'd assume that a preset is made **for** a certain model
therefor i'd say, a preset should only reference the model, not include one

in the preset file we could include metadata from the model such as author/website to display them in case of error

happy to hear your feedback
thanks

**Comment by usdivad** [comment]
Hey! Thanks for the note -- yea I think that makes sense for presets only referencing models. I would maybe advocate for putting the metadata directly in the model (to make it easier to create multiple presets with the same model), although some kind of description field for a preset could be useful too.

In any case, I'd say even just getting the existing parameters to save/load would be helpful for users.

**Comment by GuitarML** [comment]
Latest version of SmartAmp has save/load plugin states implemented, removed custom model load, implemented better in SmartGuitarPedal, closing issue.
