### ISSUE TITLE
[SUGGESTION] Collaboration with other open projects

### ISSUE THREAD

**Issue by forart** [GuitarML/SmartGuitarAmp#23]
Hi there, SGA **sounds** cool !

Since we've added it to our collection for the [HyMPS project](https://github.com/forart/HyMPS/), we strongly suggest you to check out other in order to establish some kind of collaboration that certainly could benefit all:

- https://sourceforge.net/projects/scorchcrafter/
- https://github.com/resonantdsp/SwankyAmp
- https://github.com/apohl79/GuitarAmp
- https://github.com/kaktus3000/HighGain
- https://github.com/andrepxx/go-dsp-guitar
- https://github.com/forart/ayemux

Hope that inspires !

**Comment by GuitarML** [comment]
Great idea to group these projects, there’s a lot of great open source audio software out there that deserve attention. Looking forward to any future collaboration!

**Comment by mishushakov** [comment]
GuitarML plugins are also listed on https://github.com/webprofusion/OpenAudio

**Comment by forart** [comment]
OK we updated the whole HyMPS github with a better listing.

Check out [Guitar section](https://github.com/forart/HyMPS/blob/main/GuitarDSPs.md).

Hope that inspires !

**Comment by MarcoRavich** [comment]
Update: we have a specific guitar section now.

Check it out: https://github.com/forart/HyMPS/blob/main/Guitar.md#audio---effects---guitar-
