### ISSUE TITLE
Android/iOS?

### ISSUE THREAD

**Issue by lattice0** [GuitarML/SmartGuitarAmp#26]
What are the chances on this running on Android and iOS?

**Comment by mishushakov** [comment]
it is not impossible
the main problem would be latency + battery drain

making a post-processor for applying effects on .wav would be a good start
i have made a project, which runs smaller LTSM-models in browsers: https://github.com/mishushakov/GuitarLSTM-browser works perfectly fine on mobile too!

**Comment by GuitarML** [comment]
Yes, you can definitely build for Android and iOS using the Juce framework, the question comes down to the hardware. I'd love to test it out sometime.

**Comment by GuitarML** [comment]
Issue clean up, no current plans to implement an android/iOS  for SmartAmp
