### ISSUE TITLE
SmartAmp and SmartPedal have the same plugin UID?

### ISSUE THREAD

**Issue by crenshawda** [GuitarML/SmartGuitarAmp#31]
I couldn't get Reaper 6.67 Win10 to see both until I enabled this setting:

![image](https://user-images.githubusercontent.com/215924/189487060-b7752120-10df-463d-8397-67fc6a5640b6.png)

**Comment by GuitarML** [comment]
Thanks so much for that! Yes it appears I built them with the same uid, to be honest I didn't know that it mattered until now. Will fix and update soon.

**Comment by GuitarML** [comment]
@crenshawda Here's a couple of new SmartPedal models for your assistance in diagnosing this issue, its from a Rockman distortion rackmount unit.  It's trained from the same samples as the NeuralPi Rockman models, but using WaveNet, and they sound pretty good with an IR after it. One uses a 10 layer model, and the other is a 18 layer. Enjoy!

[rockman_SmartPedal_models.zip](https://github.com/GuitarML/SmartGuitarAmp/files/9543773/rockman_SmartPedal_models.zip)

**Comment by GuitarML** [comment]
The SmartGuitarAmp and SmartGuitarPedal releases have been updated to have unique UID, verified loading both in Reaper without requiring the "same UID" setting. Closing issue
