### ISSUE TITLE
Add automation parameters

### ISSUE THREAD

**Issue by meckito** [GuitarML/SmartGuitarAmp#8]
automatable parameters are the only way for a blind user to do anything. Currently, the blind can only load the plug and process the signal on the default parameters. Nothing more.

**Comment by keyth72** [comment]
Thank you for bringing this to my attention. I’ll make it a priority to add that feature, but please be patient with me, I’ll have to learn how to do that in the code.

**Comment by GuitarML** [comment]
Added in version 1.3, closing issue
